== Interface Definition Rules

1. Interfaces cannot be instantiated directly.

2. An interface is not required to have any methods.

3. An interface may not be marked as final.

4. All top-level interfaces are assumed to have `public` or default access, and they
must include the `abstract` modifier in their definition. Therefore, marking an interface
as `private`, `protected` and `final` will trigger a compiler error, since this is
incompatible these assumptions.

5. All non-default methods in an interface are assumed to have the modifiers `abstract` and
`public` in their definition. Therefore, marking a method as `private`, `protected` or
`final` will trigger compiler errors as these are incompatible with `abstract` and `public`
keywords.

== Interface Inheritance Rules

1. An interface that extends another interface, as well as an abstract class that
implements an interface, inherits all of the abstract methods as its own abstract
methods.

2. The first concrete class that implements an interface, or extends an abstract
class that implements an interface, must provide an implementation for all the
inherited abstract methods.

== Interface Variable Definition Rules

1. Interface variables are assumed to be `public`, `static` and `final`. Therefore,
marking a variable as `private` or `protected` will trigger a compiler error, as
will marking any variable as `abstract`.

2. The value of interface variable must be set when it is declared since it is marked
as `final`.

== Default Interface Method Rules

1. A default method may only be declared within an interface and not within a class
or abstract class.

2. Default method must be marked with the `default` keyword. If a method is marked as
`default`, it must provide a method body.

3. A default method is not assumed to be `static`, `final`, or `abstract`, as it may be
used or overridden by a class that implements the interface.

4. Like all methods in an interface, a default method is assumed to be `public` and will
not compile if marked as private or protected.

== Static Interface Method Rules

1. Like all methods in an interface, a static method is assumed to be `public` and
will not compile `private` or `protected`.

2. To reference a static method, a reference to the name of the interface must be used.